
export init_XK


function init_XK!(X::AbstractVector{T}, Kcon::AbstractVector{T}, i::Int, j::Int, Xcam::AbstractVector{T}, nx::Int, ny::Int, fovx, fovy, bhspin, xoff = 0, yoff = 0) where T
    """
    Initializes a geodesic from the camera

    Parameters:
    @i: x-index of the pixel in the image plane.
    @j: y-index of the pixel in the image plane.
    @Xcam: Position vector of the camera in internal coordinates.
    @params: Parameters for the camera.
    @fovx: Field of view in the x-direction.
    @fovy: Field of view in the y-direction.
    """

    Econ = MMatrix{4,4,T}(undef)
    Ecov = MMatrix{4,4,T}(undef)
    Kcon_tetrad = MVector{4,T}(undef)

    _, Econ, Ecov = make_camera_tetrad(Xcam, bhspin)
    dxoff::Float64 = (i + 0.5 + xoff - 0.01) / nx - 0.5
    dyoff::Float64 = (j + 0.5 + yoff) / ny - 0.5
    Kcon_tetrad[1] = zero(T)
    Kcon_tetrad[2] = (dxoff * cos(zero(T)) - dyoff * sin(zero(T))) * fovx
    Kcon_tetrad[3] = (dxoff * sin(zero(T)) + dyoff * cos(zero(T))) * fovy
    Kcon_tetrad[4] = one(T)

    Kcon_tetrad = null_normalize(Kcon_tetrad, one(T))

    tetrad_to_coordinate!(Kcon, Econ, Kcon_tetrad)

    @inbounds for mu in 1:NDIM
        X[mu] = Xcam[mu]
    end

    #@printf("For pixel (%d, %d) Xcam = [%.15e, %.15e, %.15e, %.15e]\n", i, j, Xcam[1], Xcam[2], Xcam[3], Xcam[4])
    #@printf("For pixel (%d, %d) Kcon = [%.15e, %.15e, %.15e, %.15e]\n", i,j, Kcon[1], Kcon[2], Kcon[3], Kcon[4])
    #@printf("dxoff = %g, dyoff = %g\n", dxoff, dyoff)
end


function init_XK_local_tetrad(i::Int, j::Int, Xcam::MVec4, res, fovx::Float64, fovy::Float64, bhspin::Float64)
    """
    Computes the initial four-momentum of a geodesic in local tetrad coordinates.

    Parameters:
    @i: x-index of the pixel in the image plane.
    @j: y-index of the pixel in the image plane.
    @Xcam: Position vector of the camera in internal coordinates.
    @res: resolution of the image.
    @fovx: Field of view in the x-direction.
    @fovy: Field of view in the y-direction.
    """

    Econ = MMat4(undef)
    Ecov = MMat4(undef)
    Kcon = MVec4(undef)
    Kcon_tetrad = MVec4(undef)
    X = MVec4(undef)


    _, Econ, Ecov = make_camera_tetrad(Xcam, bhspin)
    dxoff::Float64 = (i + 0.5 - 0.01) / res - 0.5
    dyoff::Float64 = (j + 0.5) / res - 0.5
    Kcon_tetrad[1] = 0.0
    Kcon_tetrad[2] = (dxoff * cos(0) - dyoff * sin(0)) * fovx
    Kcon_tetrad[3] = (dxoff * sin(0) + dyoff * cos(0)) * fovy
    Kcon_tetrad[4] = 1.0

    #Put it in the order that krang uses it
    #Maybe we have to flip the first sign? Depends if Krang accepts the contravariant or covariant form
    Kcon_tetrad = null_normalize(Kcon_tetrad, 1.0)  

    Kdom = [Kcon_tetrad[1], Kcon_tetrad[4], Kcon_tetrad[2] , Kcon_tetrad[3]]

    return Kdom

end

# function BHV_C(a::Float64, θs::Float64, ro::Float64, νθ::Float64, eta::Float64, lambda::Float64, Δτ::Float64, rmax::Float64)
#     """
#     Calls trevor's C function to calculate the geodesic for a given black hole spin and camera position.
#     """

#     ccall((generateTrajectory, trevor.so), Cvoid, Cdouble, Cdouble, Cdouble, Cdouble, Cdouble, Cdouble, Cdouble, Cdouble,
#           a, θs, ro, νθ, eta, lambda, Δτ, rmax)
# end

function KrangGeoTracing(bhspin::Float64, θo::Float64, ro::Float64, fovx::Float64, fovy::Float64, npoints::Int64, nx::Int64, ny::Int64)
    """
    Calculates the geodesics uniformly in minotime for a given black hole spin and camera position.
    Parameters:
    @bhspin: Spin of the black hole.
    @θo: Polar angle of the camera.
    @ro: Radial distance of the camera from the black hole.
    @fovx: Field of view in the x-direction.
    @fovy: Field of view in the y-direction.
    @npoints: Number of geodesics points
    """

    if(nx != ny)
        error("Different number of pixels in x and y direction is not currently supported.")
    end
    #Set up the spin of the black hole for Krang
    metric = Krang.Kerr(bhspin);

    #position of the camera in native coordinates
    Xcam = camera_position(ro, θo * 180/π, 0.0, bhspin, Rout)

    
    # Calculate the four-momentum of the photon at the camera position
    Kcon = Array{Any}(undef, nx, ny)
    for i in 1:nx
        for j in 1:ny
            Kcon[i, j] = init_XK_local_tetrad(i, j, Xcam, nx, fovx, fovy, bhspin)
        end
    end


    #Initialize the camera pixel for each Kcon
    camera_k = Array{Any}(undef, nx, ny)
    for i in 1:nx
        for j in 1:ny
            camera_k[i, j] = Krang.IntensityPixel(metric, Kcon[i,j], θo, ro)
        end
    end


    #spit out the geodesics points for every pixel
    lines = [Krang.generate_ray(camera_k[i, j], npoints) for i in 1:res, j in 1:res]


    #Comment this out. This should be the rays generated by giving latitude and longitude
    #camera = Krang.IntensityCamera(metric, θo, ro,-fovx, fovx, -fovy, fovy, res);
    #lines = Krang.generate_ray.(camera.screen.pixels, geopoints)


    #This convert the lines to KS coordinates
    lines_ks = Array{Any}(undef, res * res)
    metric = Krang.Kerr(bhspin);
    for idx in eachindex(lines)
        line = lines[idx]
        lines_ks[idx] = [
            begin
                (; ts=pt.ts, rs=pt.rs, θs=pt.θs, ϕs=Krang.ϕ_kerr_schild(metric, pt.rs, pt.ϕs))
            end
            for pt in line
        ]
    end
    println("Number of rays: ", length(lines))
    return lines_ks
end

function get_pixel(traj::Vector{OfTraj}, i::Int, j::Int, Xcam::MVec4, maxnstep, fovx::Float64, fovy::Float64, freq::Float64, nx::Int64,ny::Int64, bhspin::Float64, Rh::Float64, Rout::Float64, Rstop::Float64, xoff = 0, yoff = 0)
    """
    Evolves the geodesic for each pixel.
    Parameters:
    @i: x-index of the pixel in the image plane.
    @j: y-index of the pixel in the image plane.
    @Xcam: Position vector of the camera in internal coordinates.
    @params: Parameters for the camera.
    @fovx: Field of view in the x-direction.
    @fovy: Field of view in the y-direction.
    @freq: Frequency of the radiation.
    """
    X = MVec4(undef)
    Kcon = MVec4(undef)

    init_XK!(X, Kcon, i, j, Xcam, nx,ny, fovx, fovy, bhspin, xoff, yoff)
    for mu in 1:NDIM
        Kcon[mu] *= freq
    end
    nstep = trace_geodesic(X, Kcon, traj, maxnstep, i, j, bhspin, Rh, Rout, Rstop)


    if nstep >= maxnstep - 1
        @error "Max number of steps exceeded at pixel ($i, $j)"
    end

    return nstep
end

function CalculateGeodesics(Xcam, fovx, fovy, freq_cgs, maxnstep, nx, ny, bhspin, Rout, Rstop)
    """
    Calculate the geodesics for the given camera position and field of view.
    
    Parameters:
    @Xcam: Camera position in native coordinates.
    @fovx: Field of view in x direction in radians.
    @fovy: Field of view in y direction in radians.
    @freq_cgs: Frequency in cgs units.
    @maxnstep: Maximum number of steps for the geodesic integration.
    @res: Resolution of the image (number of pixels).
    
    Returns:
    A matrix of geodesic trajectories for each pixel.
    """
    Rh = 1 + sqrt(1. - bhspin * bhspin);  # Radius of the horizon
    #println("Utilizing $(Threads.nthreads()) threads for geodesic calculation.")
    trajs = Matrix{Vector{OfTraj}}(undef, nx, ny)
    freq_unitless = freq_cgs * HPL/(ME * CL * CL)  # Convert frequency to unitless



    Threads.@threads for i in 0:(nx - 1)
        tid = Threads.threadid()
        for j in 0:(ny - 1)
            trajs[i+1, j+1] = Vector{OfTraj}()
            sizehint!(trajs[i+1, j+1], maxnstep)
            
            nstep = get_pixel(trajs[i+1, j+1], i, j, Xcam, maxnstep, fovx, fovy, freq_unitless, nx, ny, bhspin, Rh, Rout, Rstop)

            resize!(trajs[i+1, j+1], length(trajs[i+1, j+1]))
        end
    end
    return trajs
end

function get_connection_analytic!(X::AbstractVector{T}, lconn::TTensor3D, bhspin) where T
    """
    Returns the analytical connection coefficients in Kerr-Schild coordinates.

    Parameters:
    @X: Vector of position coordinates in internal coordinates.
    """
    
    r1 = exp(X[2]) 
    r2 = r1 * r1
    r3 = r2 * r1
    r4 = r3 * r1
    r,th = bl_coord(X)


    if(MODEL == "analytic" || MODEL == "thin_disk")
        th = π * X[3]
        dthdx2 = π
        d2thdx22 = 0.0
        dthdx22 = dthdx2 * dthdx2
    elseif(MODEL == "iharm")
        if(params.metric == METRIC_MKS)
            th = π * X[3] + ((1.0 - params.hslope) / 2.0) * sin(2.0 * π * X[3])
            dthdx2 = π + (1.0 - params.hslope) * π * cos(2.0 * π * X[3])
            d2thdx22 = -2.0 * π^2 * (1.0 - params.hslope) * sin(2.0 * π * X[3])
            dthdx22 = dthdx2 * dthdx2

        elseif(params.metric == METRIC_FMKS)
            error("FMKS metric is not currently supported in the analytic connection. Please use MKS metric for now.")
            # Aliases for readability
            x1 = X[2]
            x2 = X[3]
            h = params.hslope
            pn = params.poly_norm
            px = params.poly_xt
            pa = params.poly_alpha
            ms = params.mks_smooth
            x10 = params.startx[2]
            
            # 1. Base MKS angle (thG) and its derivatives w.r.t x2
            thG = π * x2 + ((1.0 - h) / 2.0) * sin(2.0 * π * x2)
            thG_p = π + (1.0 - h) * π * cos(2.0 * π * x2)
            thG_pp = -2.0 * π^2 * (1.0 - h) * sin(2.0 * π * x2)
            
            # 2. Jet angle (thJ) and its derivatives w.r.t x2
            y = 2.0 * x2 - 1.0
            u = y / px
            
            thJ = pn * y * (1.0 + (u^pa) / (pa + 1.0)) + 0.5 * π
            thJ_p = 2.0 * pn * (1.0 + (u^pa) / (pa + 1.0)) + pn * y * (pa * u^(pa - 1.0)) / (pa + 1.0) * (2.0 / px)
            thJ_pp = (8.0 * pn * pa) / (px * (pa + 1.0)) * u^(pa - 1.0) + (4.0 * pn * pa * (pa - 1.0) * y) / (px^2 * (pa + 1.0)) * u^(pa - 2.0)
            
            # 3. Radial modulation factor
            f = exp(ms * (x10 - x1))
            
            # 4. Final theta and derivatives
            th = thG + f * (thJ - thG)
            dthdx2 = thG_p + f * (thJ_p - thG_p)
            d2thdx22 = thG_pp + f * (thJ_pp - thG_pp)
            dthdx22 = dthdx2 * dthdx2
        else
            error("Unknown METRIC type: $(params.metric)")
        end
    else
        error("Unknown model: $MODEL")
    end
    # elseif(MODEL == "iharm")
    #     E = exp(params.mks_smooth * (params.startx[2] - X[2]))
    #     dthG = π * (1.0 + (1.0 - params.hslope) * cos(2.0 * π * X[3]))
    #     y = 2 * X[3] - 1.0
    #     dthJ = 2 * params.poly_norm * (1 + (y/params.poly_xt)^params.poly_alpha)
    #     dthG2 = -2 * π * π * (1.0 - params.hslope) * sin(2.0 * π * X[3])
    #     dthJ2 = 4 * params.poly_norm * params.poly_alpha * (y/params.poly_xt)^(params.poly_alpha - 1) / params.poly_xt
    #     dthdx2 = (1.0 - E) * dthG + E * dthJ
    #     d2thdx22 = (1.0 - E) * dthG2 + E * dthJ2
    #     dthdx22 = dthdx2 * dthdx2
        
    #     thG = π * X[3] + ((1. - params.hslope) / 2.) * sin(2. * π * X[3]);
    #     thJ = params.poly_norm * y* (1. + ((y / params.poly_xt)^params.poly_alpha) / (params.poly_alpha + 1.)) + 0.5 * π;

    #     dthdx1 = -params.mks_smooth * exp(params.mks_smooth * (params.startx[2] - X[2])) * (thJ - thG);
    #     d2thdx12 = params.mks_smooth^2 * exp(params.mks_smooth * (params.startx[2] - X[2])) * (thJ - thG);
    #     d2thdx1_2 = -2.0 * params.mks_smooth * exp(params.mks_smooth * (params.startx[2] - X[2])) * (dthJ - dthG);

    # else
    #     error("Unknown model: $MODEL")
    # end

    sth = sin(th)
    cth = cos(th)
    sth2 = sth * sth
    r1sth2 = r1 * sth2
    sth4 = sth2 * sth2
    cth2 = cth * cth
    cth4 = cth2 * cth2
    s2th = 2.0 * sth * cth
    c2th = 2.0 * cth2 - 1.0

    a2 = params.a * params.a
    a2sth2 = a2 * sth2
    a2cth2 = a2 * cth2
    a3 = a2 * params.a
    a4 = a3 * params.a
    a4cth4 = a4 * cth4

    rho2 = r2 + a2cth2
    rho22 = rho2 * rho2
    rho23 = rho22 * rho2
    irho2 = 1.0 / rho2
    irho22 = irho2 * irho2
    irho23 = irho22 * irho2
    irho23_dthdx2 = irho23 / dthdx2

    fac1 = r2 - a2cth2
    fac1_rho23 = fac1 * irho23
    fac2 = a2 + 2 * r2 + a2 * c2th
    fac3 = a2 + r1 * (-2.0 + r1)

    lconn[1, 1, 1] = 2.0 * r1 * fac1_rho23
    lconn[1, 1, 2] = r1 * (2.0 * r1 + rho2) * fac1_rho23
    lconn[1, 1, 3] = -a2 * r1 * s2th * dthdx2 * irho22
    lconn[1, 1, 4] = -2.0 * params.a * r1sth2 * fac1_rho23

    lconn[1, 2, 1] = lconn[1, 1, 2]
    lconn[1, 2, 2] = 2.0 * r2 * (r4 + r1 * fac1 - a4cth4) * irho23
    lconn[1, 2, 3] = -a2 * r2 * s2th * dthdx2 * irho22
    lconn[1, 2, 4] = params.a * r1 * (-r1 * (r3 + 2 * fac1) + a4cth4) * sth2 * irho23

    lconn[1, 3, 1] = lconn[1, 1, 3]
    lconn[1, 3, 2] = lconn[1, 2, 3]
    lconn[1, 3, 3] = -2.0 * r2 * dthdx22 * irho2
    lconn[1, 3, 4] = a3 * r1sth2 * s2th * dthdx2 * irho22

    lconn[1, 4, 1] = lconn[1, 1, 4]
    lconn[1, 4, 2] = lconn[1, 2, 4]
    lconn[1, 4, 3] = lconn[1, 3, 4]
    lconn[1, 4, 4] = 2.0 * r1sth2 * (-r1 * rho22 + a2sth2 * fac1) * irho23

    lconn[2, 1, 1] = fac3 * fac1 / (r1 * rho23)
    lconn[2, 1, 2] = fac1 * (-2.0 * r1 + a2sth2) * irho23
    lconn[2, 1, 3] = 0.0
    lconn[2, 1, 4] = -params.a * sth2 * fac3 * fac1 / (r1 * rho23)

    lconn[2, 2, 1] = lconn[2, 1, 2]
    lconn[2, 2, 2] = (r4 * (-2.0 + r1) * (1.0 + r1) + a2 * (a2 * r1 * (1.0 + 3.0 * r1) * cth4 + a4 * cth4 * cth2 + r3 * sth2 + r1 * cth2 * (2.0 * r1 + 3.0 * r3 - a2sth2))) * irho23
    lconn[2, 2, 3] = -a2 * dthdx2 * s2th / fac2
    lconn[2, 2, 4] = params.a * sth2 * (a4 * r1 * cth4 + r2 * (2 * r1 + r3 - a2sth2) + a2cth2 * (2.0 * r1 * (-1.0 + r2) + a2sth2)) * irho23

    lconn[2, 3, 1] = lconn[2, 1, 3]
    lconn[2, 3, 2] = lconn[2, 2, 3]
    lconn[2, 3, 3] = -fac3 * dthdx22 * irho2
    lconn[2, 3, 4] = 0.0

    lconn[2, 4, 1] = lconn[2, 1, 4]
    lconn[2, 4, 2] = lconn[2, 2, 4]
    lconn[2, 4, 3] = lconn[2, 3, 4]
    lconn[2, 4, 4] = -fac3 * sth2 * (r1 * rho22 - a2 * fac1 * sth2) / (r1 * rho23)

    lconn[3, 1, 1] = -a2 * r1 * s2th * irho23_dthdx2
    lconn[3, 1, 2] = r1 * lconn[3, 1, 1]
    lconn[3, 1, 3] = 0.0
    lconn[3, 1, 4] = params.a * r1 * (a2 + r2) * s2th * irho23_dthdx2

    lconn[3, 2, 1] = lconn[3, 1, 2]
    lconn[3, 2, 2] = r2 * lconn[3, 1, 1]
    lconn[3, 2, 3] = r2 * irho2
    lconn[3, 2, 4] = (params.a * r1 * cth * sth * (r3 * (2.0 + r1) + a2 * (2.0 * r1 * (1.0 + r1) * cth2 + a2 * cth4 + 2 * r1sth2))) * irho23_dthdx2

    lconn[3, 3, 1] = lconn[3, 1, 3]
    lconn[3, 3, 2] = lconn[3, 2, 3]
    lconn[3, 3, 3] = -a2 * cth * sth * dthdx2 * irho2 + d2thdx22 / dthdx2
    lconn[3, 3, 4] = 0.0

    lconn[3, 4, 1] = lconn[3, 1, 4]
    lconn[3, 4, 2] = lconn[3, 2, 4]
    lconn[3, 4, 3] = lconn[3, 3, 4]
    lconn[3, 4, 4] = -cth * sth * (rho23 + a2sth2 * rho2 * (r1 * (4.0 + r1) + a2cth2) + 2.0 * r1 * a4 * sth4) * irho23_dthdx2

    lconn[4, 1, 1] = params.a * fac1_rho23
    lconn[4, 1, 2] = r1 * lconn[4, 1, 1]
    lconn[4, 1, 3] = -2.0 * params.a * r1 * cth * dthdx2 / (sth * rho22)
    lconn[4, 1, 4] = -a2sth2 * fac1_rho23

    lconn[4, 2, 1] = lconn[4, 1, 2]
    lconn[4, 2, 2] = params.a * r2 * fac1_rho23
    lconn[4, 2, 3] = -2 * params.a * r1 * (a2 + 2 * r1 * (2.0 + r1) + a2 * c2th) * cth * dthdx2 / (sth * fac2 * fac2)
    lconn[4, 2, 4] = r1 * (r1 * rho22 - a2sth2 * fac1) * irho23

    lconn[4, 3, 1] = lconn[4, 1, 3]
    lconn[4, 3, 2] = lconn[4, 2, 3]
    lconn[4, 3, 3] = -params.a * r1 * dthdx22 * irho2
    lconn[4, 3, 4] = dthdx2 * (0.25 * fac2 * fac2 * cth / sth + a2 * r1 * s2th) * irho22

    lconn[4, 4, 1] = lconn[4, 1, 4]
    lconn[4, 4, 2] = lconn[4, 2, 4]
    lconn[4, 4, 3] = lconn[4, 3, 4]
    lconn[4, 4, 4] = (-params.a * r1sth2 * rho22 + a3 * sth4 * fac1) * irho23

end




function push_photon!(X::MVec4, Kcon::MVec4, dl::Float64, Xhalf::MVec4, Kconhalf::MVec4, lconn::Tensor3D, bhspin::Float64)
    """
    Pushes the photon geodesic forward/backwards by a step size dl/-dl using the analytic connection coefficients.
    Parameters:
    @X: Position vector of the photon in internal coordinates.
    @Kcon: Covariant 4-vector of the photon in internal coordinates.
    @dl: Step size for the geodesic integration.
    @Xhalf: Position vector of the photon at the half-step.
    @Kconhalf: Covariant 4-vector of the photon at the half-step.
    """

    dKcon::Float64 = 0.0

    if(MODEL == "analytic" || MODEL == "thin_disk")
        #Use analytic connection
        get_connection_analytic!(X, lconn, bhspin)
    elseif(MODEL == "iharm")
        #get_connection(X, bhspin, lconn)
        get_connection_analytic!(X, lconn, bhspin)

    else
        error("Unknown model: $MODEL")
    end 

    @inbounds for k in 1:NDIM
        @inbounds for i in 1:NDIM
            @inbounds for j in 1:NDIM
                dKcon -= 0.5 * dl * lconn[k, i, j] * Kcon[i] * Kcon[j]
            end
        end
        Kconhalf[k] = Kcon[k] + dKcon
        Xhalf[k] = X[k] + 0.5 * dl * Kcon[k]
        dKcon = 0.0
    end
        
    if(MODEL == "analytic" || MODEL == "thin_disk")
        #Use analytic connection
        get_connection_analytic!(Xhalf, lconn, bhspin)
    elseif(MODEL == "iharm")
        #get_connection(Xhalf, bhspin, lconn)
        get_connection_analytic!(Xhalf, lconn, bhspin)

    else
        error("Unknown model: $MODEL")
    end 

    dKcon = 0.0

    @inbounds for k in 1:NDIM
        @inbounds for i in 1:NDIM
            @inbounds for j in 1:NDIM
                dKcon -= dl * lconn[k, i, j] * Kconhalf[i] * Kconhalf[j]
            end
        end
        Kcon[k] += dKcon
        X[k] += dl * Kconhalf[k]
        dKcon = 0.0
    end
end

const DEL = 1.e-6
function get_connection(X::AbstractVector{T}, bhspin, conn::TTensor3D) where T
    """
    Returns the connection coefficients in Kerr-Schild coordinates using finite differences.
    Parameters:
    @X: Vector of position coordinates in internal coordinates.
    """
    tmp = similar(conn)
    Xh = copy(X)
    Xl = copy(X)
    # gcov::MMat4 = MMat4(undef)
    # gcon::MMat4 = MMat4(undef)
    # fill!(gcov, 0.0)
    # gcov_func!(X, bhspin, gcov)
    # gcon_func!(gcov, gcon)

    gcov = gcov_func(X, bhspin)
    gcon = gcon_func(gcov)
    
    @inbounds for k in 1:NDIM
        Xh .= X
        Xl .= X
        Xh[k] += DEL
        Xl[k] -= DEL

        gh = gcov_func(Xh, bhspin)
        gl = gcov_func(Xl, bhspin)



        @inbounds for i in 1:NDIM
            @inbounds for j in 1:NDIM
                conn[i, j, k] = (gh[i, j] - gl[i, j]) / (Xh[k] - Xl[k])
            end
        end
    end


    @inbounds for i in 1:NDIM
        @inbounds for j in 1:NDIM
            @inbounds for k in 1:NDIM
                tmp[i, j, k] = 0.5 * (conn[j, i, k] + conn[k, i, j] - conn[k, j, i])
            end
        end
    end

    @inbounds for i in 1:NDIM
        @inbounds for j in 1:NDIM
            @inbounds for k in 1:NDIM
                s = 0.0 #s here reduces the amount of allocations
                for l in 1:NDIM
                    s += gcon[i,l] * tmp[l,j,k]
                end
                conn[i,j,k] = s
            end
        end
    end
    return conn
end


function stepsize(X::MVec4, Kcon::MVec4, cstartx::MVec4, cstopx::MVec4, eps_ipole::Float64 = 0.01)
    """
    Computes the step size for the geodesic integration based on the position and covariant 4-vector.
    Parameters:
    @X: Position vector of the photon in internal coordinates.
    @Kcon: Covariant 4-vector of the photon in internal coordinates.
    @eps: Small constant for controlling the step size.
    """
    dlx2::Float64 = 0.0
    dlx3::Float64 = 0.0
    dlx4::Float64 = 0.0
    idlx2::Float64 = 0.0
    idlx3::Float64 = 0.0
    idlx4::Float64 = 0.0
    dl::Float64 = 0.0

    
    if(true)
        deh::Float64 = min(abs(X[2] - cstartx[2]), 0.1)
        dlx2 = eps_ipole * (10 * deh) / (abs(Kcon[2]) + SMALL*SMALL)
        cut::Float64 = 0.002
        lx3::Float64 = cstopx[3] - cstartx[3]
        dpole::Float64 = min(abs(X[3] / lx3), abs((cstopx[3] - X[3]) / lx3))
        d2fac::Float64 = (dpole < cut) ? dpole / 3 : min(cut / 3 + (dpole - cut) * 10., 1)
        dlx3 = eps_ipole * d2fac / (abs(Kcon[3]) + SMALL*SMALL)

        dlx4 = eps_ipole / (abs(Kcon[4]) + SMALL*SMALL)
        idlx2 = 1.0 / (abs(dlx2) + SMALL*SMALL)
        idlx3 = 1.0 / (abs(dlx3) + SMALL*SMALL)
        idlx4 = 1.0 / (abs(dlx4) + SMALL*SMALL)

        dl = 1.0 / (idlx2 + idlx3 + idlx4)
    else
        dlx2 = eps_ipole / (abs(Kcon[2]) + SMALL*SMALL)
        dlx3 = eps_ipole * min(X[3], 1. - X[3]) / (abs(Kcon[3]) + SMALL*SMALL)
        dlx4 = eps_ipole / (abs(Kcon[4]) + SMALL*SMALL)

        idlx2 = 1.0 / (abs(dlx2) + SMALL*SMALL)
        idlx3 = 1.0 / (abs(dlx3) + SMALL*SMALL)
        idlx4 = 1.0 / (abs(dlx4) + SMALL*SMALL)

        dl = 1.0 / (idlx2 + idlx3 + idlx4)
    end
    return dl
end


function stop_backward_integration(X::MVec4, Kcon::MVec4, Rh::Float64, Rstop::Float64)
    """
    Checks if the backward integration should stop based on the position and covariant 4-vector.
    Parameters:
    @X: Position vector of the photon in internal coordinates.
    @Kcon: Covariant 4-vector of the photon in internal coordinates.
    """
    if (((X[2] > log(Rstop)) && (Kcon[2] < 0.0)) || (X[2] < log(Rh+ 0.0001)))
        return 1
    end

    return 0
end

function trace_geodesic(Xi::MVec4, Kconi::MVec4, traj::Vector{OfTraj}, step_max::Int, i::Int, j::Int, bhspin::Float64, Rh::Float64, Rout::Float64, Rstop::Float64)
    """
    Function loops through the geodesic integration steps, pushing the photon along the geodesic.
    Parameters:
    @Xi: Initial position vector of the photon in internal coordinates.
    @Kconi: Initial covariant 4-vector of the photon in internal coordinates.
    @traj: Structure to store the trajectory of the photon.
    @eps: Small constant for controlling the step size.
    @step_max: Maximum number of steps for the geodesic integration.
    @i: x-index of the pixel in the image plane (debugging purposes).
    @j: y-index of the pixel in the image plane (debugging purposes).
    """
    
    X = copy(Xi)
    Kcon = copy(Kconi)
    Xhalf = copy(Xi)
    Kconhalf = copy(Kconi)

    push!(traj, OfTraj(
        0,
        copy(Xi),   
        copy(Kconi),   
        copy(Xi),   
        copy(Kconi),
        MVec4(undef), #This is dX_dθo for the derivatives in autodiff
        MVec4(undef),  #This is dK_dθo for the derivatives in autodiff
        MVec4(undef),  #This is dX_da for the derivatives in autodiff
        MVec4(undef)  #This is dK_da for the derivatives in autodiff
    ))
    nstep = 1
    lconn = Tensor3D(undef)
    while (stop_backward_integration(X, Kcon, Rh, Rstop) == 0) && (nstep < step_max)
        dl = stepsize(X, Kcon, params.cstartx, params.cstopx)

        traj[nstep].dl = dl * L_unit * HPL / (ME * CL^2)


        push_photon!(X, Kcon, -dl, Xhalf, Kconhalf, lconn, bhspin)

        nstep += 1
        push!(traj, OfTraj(
            copy(dl),
            copy(X),   
            copy(Kcon),   
            copy(Xhalf),   
            copy(Kconhalf),
            MVec4(undef), #This is dX_dθo for the derivatives in autodiff
            MVec4(undef),  #This is dK_dθo for the derivatives in autodiff
            MVec4(undef),  #This is dX_da for the derivatives in autodiff
            MVec4(undef)  #This is dK_da for the derivatives in autodiff
        ))
    end
    # println("Pixel ($i, $j): Number of steps = $nstep")
    # println("  Final position: r = $(exp(X[2])), θ = $(X[3]), ϕ = $(X[4])")
    # error()
    return nstep
end


